// Learn the move-grammar ONCE from a held-out text and freeze it.
//
// The grammar is the predictor's only learned component — a bigram transition
// matrix over the ten-symbol move alphabet. It is learned here from a text the
// predictor will NOT be tested on (data/metamorphosis.txt by default), so it never
// sees the reading it predicts, and written to src/predict/grammar-data.js as a
// frozen module the predictor imports. Ten symbols, one small matrix, learned once.
//
//   node scripts/learn-grammar.mjs [data/metamorphosis.txt ...]

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ingestText } from '../src/organs/in/index.js';
import { buildMoveLog, MOVE_ALPHABET, learnGrammar } from '../src/predict/index.js';

const root = new URL('..', import.meta.url);
const sources = process.argv.slice(2).length
  ? process.argv.slice(2)
  : ['data/metamorphosis.txt'];

const moveLogs = [];
for (const rel of sources) {
  const text = readFileSync(new URL(rel, root), 'utf8');
  const doc = await ingestText(text, {});
  const { moves } = buildMoveLog(doc);
  moveLogs.push(moves);
  console.log(`  ${rel.padEnd(28)} ${doc.units.length} units → ${moves.length} moves`);
}

const grammar = learnGrammar(moveLogs, MOVE_ALPHABET, { alpha: 1 });
grammar.source = sources.join(', ');

const out = `// GENERATED by scripts/learn-grammar.mjs — do not edit by hand.
//
// The frozen move-grammar: a bigram transition matrix over the move alphabet,
// learned once from held-out text (${grammar.source}) so it never sees the reading
// it predicts. Regenerate with \`node scripts/learn-grammar.mjs\`.

export const DEFAULT_GRAMMAR = Object.freeze(${stringify(grammar)});
`;

const dest = fileURLToPath(new URL('src/predict/grammar-data.js', root));
writeFileSync(dest, out);
console.log(`\n  wrote ${dest}`);
console.log(`  marginal: ${MOVE_ALPHABET.map(op => `${op} ${grammar.marginal[op].toFixed(3)}`).join('  ')}`);

// Pretty-print the grammar object as readable, stable JS (sorted keys, compact rows).
function stringify(g) {
  const rows = MOVE_ALPHABET.map(prev => {
    const row = MOVE_ALPHABET.map(op => `${op}: ${g.trans[prev][op]}`).join(', ');
    return `    ${prev}: { ${row} }`;
  }).join(',\n');
  const marg = MOVE_ALPHABET.map(op => `${op}: ${g.marginal[op]}`).join(', ');
  return `{
  alphabet: ${JSON.stringify(g.alphabet)},
  trans: {
${rows}
  },
  marginal: { ${marg} },
  source: ${JSON.stringify(g.source)},
}`;
}
